### PR TITLE
Bug 1898487: Node is not removed when VM has been removed from oVirt engine

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
We needed to add logic to remove a node once it is not found on the oVirt Engine
See comment https://bugzilla.redhat.com/show_bug.cgi?id=1898487#c3

Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

### CODE REVIEW

**Comment by Gal-Zaidman** [comment]
/hold
need to test manually

**Comment by Gal-Zaidman** [comment]
/unhold

Installed it on a running 4.7 cluster and manually deleted the node from OCP, saw that the node object is removed from the OCP cluster and that the machine is on failed phase

**Review by eslutsky — APPROVED** [review]

**Pull request merged**
