### PR TITLE
Bug 2094806: Update dependencies to K8s 1.24, go 1.18

### PR DESCRIPTION
**Pull request by damdo**
- Update the dependencies to K8s 1.24.
- Bump project to go 1.18.

### CODE REVIEW

**Comment by damdo** [comment]
PTAL @eslutsky @janosdebugs

**Review by ghost — APPROVED** [review]
/lgtm

**Comment by janosdebugs** [comment]
@damdo do you want this to get into 4.11? If yes, this will need a BZ or staff engineer approval, plus @mburman5 needs to know.

**Comment by janosdebugs** [comment]
@damdo it seems like you are using one BZ for multiple pull requests. This will make it impossible for OCP on RHV QE to mark the RHV part as verified and it will also cause state management issues with the CI as far as I remember. You may want to open separate bugs for every provider to avoid that.

**Comment by damdo** [comment]
Hey @janosdebugs,
thanks for the review! I added the BZ.
Let's hold this for now and see what @mburman5 thinks.

**Comment by damdo** [comment]
>  You may want to open separate bugs for every provider to avoid that.

Done. I created and now linked a separate BZ. Thanks!
/assign @mburman5

**Comment by mburman5** [comment]
HI, thanks for the bz.
We will ensure no regression to the machine object side.

**Pull request merged**
