### PR TITLE
Bug 1937694: providerIDController ignore nodes that have no machine

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
If the user creates a node with no machine, for example with[1], we don't want to interfere with OpenShift logic.

[1] https://docs.openshift.com/container-platform/4.7/machine_management/user_infra/adding-bare-metal-compute-user-infra.html

### CODE REVIEW

**Comment by Gal-Zaidman** [comment]
/assign @JoelSpeed 

Please review this change, this should solve the issue we talked about on slack thread regarding the baremetal node with no machine

**Review by eslutsky — APPROVED** [review]

**Comment by JoelSpeed** [comment]
I don't think this is the correct fix for the long term. Your ProviderID controller needs to only look at Nodes with `ovirt:///...` provider IDs (this is what other Node controllers do). Ignoring machines with no Machine caters to a very specific use case but will just cause bugs later down the line if there was ever to be a scenario where we allow oVirt machines and BareMetal machines to co-exist within the same cluster.

In the normal Node controller, it has no idea what a Machine is, it just removes the Node if the provider ID is of the correct form (prefix with correct provider) and the ID no longer exists on the infrastructure provider. This controller should behave in the same way

**Comment by Gal-Zaidman** [comment]
> I don't think this is the correct fix for the long term. Your ProviderID controller needs to only look at Nodes with `ovirt:///...` provider IDs (this is what other Node controllers do).

So it will be a problem to add such logic to the providerIdController... since it sets the provider ID then at least at the beginning he will get nodes with no provider id on them and we can't ignore those since this will just break everything :)
What we can do is to separate it into 2 controllers:
- providerID controller - that will handle provider ID.
- node controller - that will handle node related stuff.

We didn't do it so far because we have nowhere to really deploy the node controller.
I asked this on your slack[2] once regarding an enhancement I came across[1] I understood that if it will get merged we could start having normal controllers like the rest of the in tree providers now have.

> Ignoring machines with no Machine caters to a very specific use case but will just cause bugs later down the line if there was ever to be a scenario where we allow oVirt machines and BareMetal machines to co-exist within the same cluster.

This will allow ovirt machine to coexist with metal nodes... tose BareMetal machines have any providerID set? I understood that they have nothing so we can't handle that in this controller (if we would split the logic into 2 controllers I guess that will be possible).

> In the normal Node controller, it has no idea what a Machine is, it just removes the Node if the provider ID is of the correct form (prefix with correct provider) and the ID no longer exists on the infrastructure provider. This controller should behave in the same way

I agree, that would force us to split the logic into 2 controllers.
Do you think we should wait for a better why or just split now and have both controllers run under the machine-controllers container?

[1] https://github.com/openshift/enhancements/pull/463
[2] https://coreos.slack.com/archives/CBZHF4DHC/p1611675378017500

**Comment by JoelSpeed** [comment]
Maybe I'm misunderstanding, but these seem like two separate issues with different conditions that could both be accounted for (and yes, would be easier as two controllers as you've suggested)

The logic that adds providerIDs:
- If Node already has providerID, ignore
- If Node doesn't have providerID, attempt to find it from oVirt/(Machine with oVirt spec)
- If Node doesn't have providerID and isn't oVirt, error and look again later (in theory the baremetal should get an ID at some point, or is that not the case?

The logic that deletes nodes:
- If no providerID, ignore
- if providerID not prefixed with ovirt, ignore
- if ovirt providerID and this vm no longer exists on provider, remove

> We didn't do it so far because we have nowhere to really deploy the node controller.

Is there anything preventing this from being another controller in the same binary as the existing providerID controller? 

> I asked this on your slack[2] once regarding an enhancement I came across[1] I understood that if it will get merged we could start having normal controllers like the rest of the in tree providers now have.

Ultimately this would be the correct place to put this but it's not ready yet, you should be able to have the logic as another control loop within your machine controller binary I would have thought, eg like you have with the providerID https://github.com/openshift/cluster-api-provider-ovirt/blob/19ab13e18ddda1d037af05a441e87d675db71480/cmd/manager/main.go#L157

> Do you think we should wait for a better why or just split now and have both controllers run under the machine-controllers container?

I should really read everything before starting to reply, we are on the same page here (leaving my original comments for prosperity). I would lean towards splitting the two control loops based on the logic that I've suggested above and run them both in the same binary for now, long term these can be split once the out of tree stuff is a bit clearer

**Comment by Gal-Zaidman** [comment]
I think we can seperate it into 2 controllers like you suggested for now.

Regarding the BareMetal machine, I don't know I don't think that it gets a provider ID but I never tried that

**Comment by Gal-Zaidman** [comment]
@JoelSpeed   Changed the implementation to fit what we agreed on,

Tested the following flows:
- scaling up
- deleting a node from ovirt, see that it reflects on nodes and machines objects
- having bare metal node running along with the ovirt nodes

**Comment by orenc1** [comment]
Tested and verified on a 4.7.0 oVirt-based OCP cluster, with 3 BM nodes without ProviderID and machines.
Thank you very much.

**Comment by JoelSpeed** [comment]
Have had a look at the updated logic and it looks good from my perspective. I didn't do a thorough code quality review though, would you prefer one?

**Comment by Gal-Zaidman** [comment]
> Have had a look at the updated logic and it looks good from my perspective. I didn't do a thorough code quality review though, would you prefer one?

If you can then sure, feel free to lgtm and remove the hold if all looks good since it has been tested

**Comment by JoelSpeed** [comment]
I don't have anything else to add, I think this is good to go

/lgtm

**Comment by orenc1** [comment]
Thanks @Gal-Zaidman and @JoelSpeed!
Can you please open a backport to 4.7?

**Pull request merged**
