### PR TITLE
Bug 1949231: Add validation for empty osDisk

### PR DESCRIPTION
**Pull request by dougsland**
Error must be raised in case users do not provide SizeGB for osDisk.

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

### CODE REVIEW

**Comment by dougsland** [comment]
need to be tested, @mgold1234 do you mind to help testing? 
Getting:
```
FATAL failed to fetch Metadata: failed to fetch dependency of "Metadata": failed to fetch dependency of "Cluster ID": failed to generate asset "Install Config": [platform.ovirt.affinityGroups: Invalid value: ovirt.AffinityGroup{Name:"compute", Priority:3, Description:"AffinityGroup for spreading each compute machine to a different host", Enforcing:true}: Affinity Group compute cannot be fulfilled, oVirt cluster doesn'thave enough hosts: found 2 hosts but 3 replicas assigned to affinity group, platform.ovirt.affinityGroups: Invalid value: ovirt.AffinityGroup{Name:"controlplane", Priority:5, Description:"AffinityGroup for spreading each control plane machine to a different host", Enforcing:true}: Affinity Group controlplane cannot be fulfilled, oVirt cluster doesn'thave enough hosts: found 2 hosts but 3 replicas assigned to affinity group] 
```

```
export OPENSHIFT_RELEASE_VERSION=4.8
export MIRROR="mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview/latest-${OPENSHIFT_RELEASE_VERSION}"
export OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE="$(curl -s -l "${MIRROR}/release.txt" | sed -n 's/^Pull From: //p')"
./bin/openshift-install create cluster --dir=ocp --log-level=debug
```

**Review by eslutsky — APPROVED** [review]

**Comment by Gal-Zaidman** [comment]
@dougsland  have you verified this change?

**Comment by Gal-Zaidman** [comment]
closing since it will be a part of the refacafor of the provider

**Pull request closed without merging**
