### PR TITLE
Bug 1926346: move to go 1.15 and registry.ci.openshift.org

### PR DESCRIPTION
**Pull request by Gal-Zaidman**

### CODE REVIEW

**Review by dougsland — CHANGES_REQUESTED** [review]
The patch looks good to me but having "explicit" word is too generic (IMO) and I am not sure if the explicit means the above commented code is "explicit" in the new import or something different. If yes, shouldn't be enough to remove old imports? 

If possible, please leave a little bit more explanation here. Today make sense but in 6 months we will need to somehow refresh our memory :)

**Comment by Gal-Zaidman** [comment]
> The patch looks good to me but having "explicit" word is too generic (IMO) and I am not sure if the explicit means the above/bellow commented code is "explicit" in the new import or something different. If yes, shouldn't be enough to remove old imports?
> 
> If possible, please leave a little bit more explanation here. Today might looks good or "obvious" but in 6 months we will need to somehow refresh our memory :)

All I did is replace the go version to 15 the in go go.mod and dockerfile.
The go.sum and everything in the vendor dir is autogenerated :)

**Comment by dougsland** [comment]
> > The patch looks good to me but having "explicit" word is too generic (IMO) and I am not sure if the explicit means the above/bellow commented code is "explicit" in the new import or something different. If yes, shouldn't be enough to remove old imports?
> > If possible, please leave a little bit more explanation here. Today might looks good or "obvious" but in 6 months we will need to somehow refresh our memory :)
> 
> All I did is replace the go version to 15 the in go go.mod and dockerfile.
> The go.sum and everything in the vendor dir is autogenerated :)

oh boy :) In that case, nothing in our side.
/lgtm

**Pull request merged**
